version: "3"

services:
  # Core API services are pinned, HA is provided for functions.
  gateway:
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        - 8080:8080
    image: functions/gateway:0.6.2
    networks:
        - functions
    environment:
         faas_nats_address: "nats"
         faas_nats_port: 4222
         dnsrr: "true"  # Temporarily use dnsrr in place of VIP while issue persists on PWD
    deploy:
        placement:
            constraints: [node.role == manager]

  nats:
        image: nats-streaming:0.5.0
        ports:
            - 4222:4222
            - 8222:8222
        command: "--store memory --cluster_id faas-cluster"
        networks:
            - functions
  queue-worker:
        image: functions/queue-worker:0.1.1
        networks:
            - functions
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 20
                window: 380s


  cron:
    image: vfarcic/docker-flow-cron
    networks:
      - functions
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9080:8080
    deploy:
      placement:
        constraints: [node.role == manager]

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - functions
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://cron:8080/v1/docker-flow-cron/job/create
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://cron:8080/v1/docker-flow-cron/job/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  #cronjob:
  #  image: alpine
  #  command: wget http://gateway:8080/function/url_ping --post-data="http://jmkhael.io/"
  #  networks:
  #    - functions
  #  deploy:
      #replicas: 0
  #    restart_policy:
  #      condition: none
#    labels:
#      - "com.df.notify=true"
#      - "com.df.cron=true"
#      - "com.df.cron.name=cronjob"
#      - "com.df.cron.image=alpine"
#      - "com.df.cron.command=echo Hello World"
#      - "com.df.cron.schedule=@every 10s"

networks:
    functions:
        driver: overlay
        #attachable: true
